[package]
name = "mytorrent_r"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2"
sha2 = "0.10"
log = "0.4"
env_logger = "0.11"
rand = "0.8"
hex = "0.4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }